#!/bin/bash
number=i

until [ $number = "q" ]; do
echo "Enter a number between 1 and 7:"

read number


case $number in
1)
echo "Red"
;;
2)
echo "Orange"
;;
3)
echo "Yellow"
;;
4)
echo "Green"
;;
5)
echo "Blue"
;;
6)
echo "Indigo"
;;
7)
echo "Violet"
;;
*)
echo "Error"
;;
esac
done
if [ $number = q ]
then
echo "Goodbye"
fi
